services:
  mymongo:
    image: mongo
    volumes:
      - ./data:/data/db

  dbbrowser:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb://mymongo:27017
    depends_on:
      - mymongo

  api:
    build: ./checker
    image: app:1.0.0
    depends_on:
      - mymongo

  web:
    build: ./plot
    image: plot:1.0.0
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - api
    